[custom]

;规则集定义
ruleset=🛡️ AdBlock,clash-domain:https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
ruleset=📹 YouTube,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=💠 Microsoft,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/mihomo-ruleset/microsoft-cn.list
ruleset=🍀 Google,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/mihomo-ruleset/google-cn.list
ruleset=🤖 AI,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/mihomo-ruleset/ai.list
ruleset=📲 Telegram,clash-ipcidr:https://github.com/DustinWin/geoip/releases/download/ips/telegramip.list
ruleset=🆓 EMBYFORFREE,clash-classic:https://raw.githubusercontent.com/witherleaves/ini-/refs/heads/main/EMBYforfree.yaml
ruleset=📺 EMBY,clash-classic:https://raw.githubusercontent.com/witherleaves/ini-/refs/heads/main/emby.yaml
ruleset=💬 论坛,clash-classic:https://raw.githubusercontent.com/witherleaves/ini-/refs/heads/main/luntan.yaml
ruleset=🎨 Pixiv,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Pixiv/Pixiv.yaml
ruleset=🍿 番剧,clash-classic:https://raw.githubusercontent.com/witherleaves/ini-/refs/heads/main/fanju.yaml
ruleset=🐙 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🎞️ Globalmedia,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml
ruleset=🚀 节点选择,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical.yaml
ruleset=🏠 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🏠 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🏠 全球直连,clash-ipcidr:https://github.com/DustinWin/geoip/releases/download/ips/privateip.list
ruleset=🏠 全球直连,clash-domain:https://github.com/DustinWin/domain-list-custom/releases/download/domains/private.list
ruleset=🏠 全球直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml
ruleset=🏠 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🏠 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=💠 Microsoft`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🎨 Pixiv`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🎞️ Globalmedia`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT

custom_proxy_group=🆓 EMBYFORFREE`select`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=📺 EMBY`select`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🌍 其他地区`[]🏡 家宽节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🍿 番剧`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=💬 论坛`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🐙 GitHub`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT
custom_proxy_group=🏠 全球直连`select`[]DIRECT`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换
custom_proxy_group=🛡️ AdBlock`select`[]REJECT`[]DIRECT`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]🇭🇰 香港节点`[]⚖️ 香港均衡`[]💰 便宜香港节点`[]🇯🇵 日本节点`[]⚖️ 便宜日本均衡`[]🔄 日本故转`[]🇸🇬 新加坡节点`[]⚖️ 便宜新加坡均衡`[]🔄 新加坡故转`[]🇺🇸 美国节点`[]💰 便宜美国节点`[]🇪🇺 欧盟节点`[]💰 便宜欧盟节点`[]🛠️ 手动切换`[]DIRECT

custom_proxy_group=🛠️ 手动切换`select`.*
custom_proxy_group=🏡 家宽节点`select`(家宽|家庭)

custom_proxy_group=💰 便宜美国节点`url-test`!!GROUPID=!0!!(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))`http://www.gstatic.com/generate_204`250,5,100
custom_proxy_group=💰 便宜香港节点`url-test`!!GROUPID=!0!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))`http://www.gstatic.com/generate_204`250,5,100
custom_proxy_group=🇭🇰 香港节点`url-test`!!GROUPID=!1!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(深港|US|家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`!!GROUPID=!1!!(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`!!GROUPID=!1!!(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`!!GROUPID=!1!!(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 其他地区`select`!!GROUPID=!1!!(^(?!.*(香港|HK|Hong Kong|🇭🇰|HongKong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|新加坡|坡|狮城|SG|Singapore)).*)
custom_proxy_group=🔄 日本故转`fallback`!!GROUPID=!1!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)(?!.*(深港|家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔄 新加坡故转`fallback`!!GROUPID=!1!!(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 香港均衡`load-balance`!!GROUPID=!1!!(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))^((?!(家宽|游戏|剩余|流量|0.5|0.5倍|0.5x|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x|5.0|5倍|5x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 便宜日本均衡`load-balance`!!GROUPID=!0!!(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚖️ 便宜新加坡均衡`load-balance`!!GROUPID=!0!!(?=.*(新加坡|坡|狮城|SG|Singapore))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=💰 便宜欧盟节点`url-test`!!GROUPID=!0!!(?=.*(欧盟|EU|英国|UK|英格兰|United Kingdom|GB|德国|DE|法国|FR|意大利|IT|西班牙|ES|荷兰|NL|比利时|BE|卢森堡|LU|奥地利|AT|爱尔兰|IE|丹麦|DK|芬兰|FI|瑞典|SE|波兰|PL|捷克|CZ|匈牙利|HU|斯洛伐克|SK|斯洛文尼亚|SI|希腊|GR|葡萄牙|PT|保加利亚|BG|罗马尼亚|RO|克罗地亚|HR|马耳他|MT|塞浦路斯|CY))`http://www.gstatic.com/generate_204`250,5,100
custom_proxy_group=🇪🇺 欧盟节点`select`!!GROUPID=!0!!(?=.*(欧盟|EU|英国|UK|英格兰|United Kingdom|GB|德国|DE|法国|FR|意大利|IT|西班牙|ES|荷兰|NL|比利时|BE|卢森堡|LU|奥地利|AT|爱尔兰|IE|丹麦|DK|芬兰|FI|瑞典|SE|波兰|PL|捷克|CZ|匈牙利|HU|斯洛伐克|SK|斯洛文尼亚|SI|希腊|GR|葡萄牙|PT|保加利亚|BG|罗马尼亚|RO|克罗地亚|HR|马耳他|MT|塞浦路斯|CY))`http://www.gstatic.com/generate_204`250,5,100
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50


;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true
